<?php $retailstore = $this->getCurrentRetailStore(); ?>
    <p><a href="<?php echo $this->getUrl('stores_retaildirectory/index/index') ?>" title="<?php echo $this->__('Back to Retail Store Directory'); ?>"><?php echo $this->__('&laquo; Back to Retail Store Directory'); ?></a></p>
</br>
    <style>
        #map {
            height: 300px;
            width: 100%;
        }
    </style>
<?php if ($retailstore): ?>
    </br>
<h1><?php echo $retailstore->getName(); ?></h1>
    <p><a href="<?php echo $this->helper('stores_retaildirectory/retailstore')->getRetailStoreUrl($retailstore); ?>" title="<?php echo $this->escapeHtml($retailstore->getName()); ?>"><?php echo $retailstore->getName(); ?></a></p>

    <h3 style="color: #de036f">Address </h3><?php echo $retailstore->getAddressLine_1(); ?> </br>
    <?php echo $retailstore->getAddressLine_2(); ?> </br>
    <?php echo $retailstore->getPostcode();?> </br>
    </br>
    <h3><strong>Openning Hours</strong></h3>
    <p style="color: #008AFF">Mon-Fri:</p><?php $date = new DateTime($retailstore->getDaily_open()); echo $date->format('H:i'); ?><?php $date = new DateTime($retailstore->getDaily_closed()); echo "-".$date->format('H:i'); ?> </br>

    <?php $date = new DateTime($retailstore->getSat_open());
    if ($date->format('H:i:s') == '00:00:00'){
        echo     '<p style="color: red">Sat-Sun</p>'.'Closed';
    } else {

        echo '<p style="color: red">Sat </p>'.$date->format('H:i');
        $date = new DateTime($retailstore->getSat_closed()); echo "-".$date->format('H:i');
        echo '<p style="color: red">Sun</p>';
        $date = new DateTime($retailstore->getSun_open());
        if ($date->format('H:i:s') == '00:00:00'){
            echo 'Closed';
        } else {
            echo $date->format('H:i');
            $date = new DateTime($retailstore->getSun_closed()); echo "-".$date->format('H:i');
        }
    }
    ?>
    </br>
    </br>

    <h2 style="color: #006AA9">Status </h2>
    <?php $day = date("l");
        $date_cur = new DateTime();
    $date_cur = strtotime($date_cur->format('H:i:s'));
    $time = date("h:i");

       if($day != 'Saturday' && $day != 'Sunday') {
            $date_open = strtotime($retailstore->getDaily_open());
            $date_close = strtotime($retailstore->getDaily_closed());
            $diff = $date_open - $date_cur;
            $time = date('H', $diff);

            if ($date_cur <= $date_close) {
                echo '<h3 style="color: #00aa00">Open</h3>';
            }
            elseif ($date_cur <= $date_open && $date_cur >= $date_close) {
                echo '<h3 style="color: #EE0000">Closed</h3>';
                echo 'Will be opened in '.$time.' hour(s)';
            }
        }
        else {
            if($day == 'Saturday'){
                $date_open = strtotime($retailstore->getSat_open());
                $date_close = strtotime($retailstore->getSat_closed());
                $diff = $date_open - $date_cur;
                $time = date('H', $diff);
                if ($date_cur >= $date_open && $date_cur <= $date_close) {
                    echo '<h3 style="color: #00aa00">Open</h3>';
                } else {
                    echo '<h3 style="color: #EE0000">Closed</h3>';
                    echo 'Will be opened in '.$time.' hour(s)';
                }
            } else {
                $date_open = strtotime($retailstore->getSun_open());
                $date_close = strtotime($retailstore->getSun_closed());
                $diff = $date_open - $date_cur;
                $time = date('H', $diff);
                 if ($date_cur >= $date_open && $date_cur <= $date_close) {
                     echo '<h3 style="color: #00aa00">Open</h3>';
                 } else {
                     echo '<h3 style="color: #EE0000">Closed</h3>';
                     echo 'Will be opened in '.$time.' hour(s)';
                 }
            }


        }

    ?>

    <h3 style="color: #3c763d"><?php echo $retailstore->getName();?> on the map</h3>
    <div id="map"></div>
    <script>

         var map, infoWindow;

        function initMap() {

            map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: <?php echo $retailstore->getLatitude();?>, lng: <?php echo $retailstore->getLongitude();?>},
                zoom: 15
            });
            infoWindow = new google.maps.InfoWindow;

            // Try HTML5 geolocation.
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };

                    var rs_pos = {
                        lat: <?php echo $retailstore->getLatitude(); ?>,
                        lng: <?php echo $retailstore->getLongitude(); ?>
                    };

                    var locations = [
                      [pos.lat, pos.lng, 0],
                        [rs_pos.lat, rs_pos.lng, 1]
                    ];

                    infoWindow = new google.maps.InfoWindow({});
                    var i, marker;
                    for(i=0; i<locations.length; i++){

                         marker = new google.maps.Marker({
                            position: new google.maps.LatLng(locations[i][0], locations[i][1]),
                             map: map,
                             title: locations[i][1]
                         });

//                        var content = locations[1][0];
                        var content = marker.title;
                        google.maps.event.addListener(marker, 'click', (function (marker, content, infoWindow, i) {
                            return function() {
                                infoWindow.setContent(content);
                                infoWindow.open(map, marker);
//                                map.setcenter(rs_pos);
                            }
                        }) (marker, content, infoWindow, i));
                    }

                }, function() {
                    handleLocationError(true, infoWindow, map.getCenter());
                });
            } else {
                // Browser doesn't support Geolocation
                handleLocationError(false, infoWindow, map.getCenter());
            }
        }

         function handleLocationError(browserHasGeolocation, infoWindow, pos) {
             infoWindow.setPosition(pos);
             infoWindow.setContent(browserHasGeolocation ?
                 'Error: The Geolocation service failed.' :
                 'Error: Your browser doesn\'t support geolocation.');
             infoWindow.open(map);

//            var retailstore = {
//                info: '<strong><?php //echo $retailstore->getName();?>//</strong><br><strong><?php //echo $retailstore->getAddressLine_1();?>//</strong><br><strong><?php //echo $retailstore->getAddressLine_2();?>//</strong><br><strong><?php //echo $retailstore->getPostcode();?>//</strong>',
//                lat: <?php //echo $retailstore->getLatitude(); ?>// ,
//               lng: <?php //echo $retailstore->getLongitude(); ?>
//            };
//            var currentloc = {
//                info: '<strong>You are here</strong>',
//                lat: 53.483529 ,
//                lng: -2.247849
//            };
//
//            var locations = [
//                [retailstore.info, retailstore.lat, retailstore.lng, 0],
//                [currentloc.info, currentloc.lat, currentloc.lng, 1]
//            ];
//
//            var map = new google.maps.Map(document.getElementById('map'), {
//                zoom: 13,
//                center: new google.maps.LatLng(<?php //echo $retailstore->getLatitude(); ?>//, <?php //echo $retailstore->getLongitude(); ?>//),
//                mapTypeId: google.maps.MapTypeId.ROADMAP
//            });
//            var infowindow = new google.maps.InfoWindow({});
//            var marker, i;
//            for(i = 0; i < locations.length; i++){
//                marker = new google.maps.Marker({
//                    position: new google.maps.LatLng(locations[i][1], locations[i][2]),
//                    map: map
//                });
//
//                google.maps.event.addListener(marker, 'click', (function (marker, i){
//                    return function(){
//                        infowindow.setContent(locations[i][0]);
//                        infowindow.open(map, marker);
//                    }
//                })(marker, i));
//            }
        }



    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDuVgopsEt13-HojbnKXYum8WtOpjOTdDs&callback=initMap">
    </script>
    </br>
    </br>
    <?php $productCollection = $this->getRetailStoreProductCollection(); ?>
    <?php if($productCollection->count() > 0): ?>
        <h2>Products</h2>
        <ul>
            <?php foreach ($productCollection as $product): ?>
             <li><a href="<?php echo $this->getUrl('catalog/product/view', array('id' => $product->getId())); ?>" title="<?php echo $this->escapeHtml($product->getName()); ?>"><?php echo $product->getName();?></a></li>
          <?php endforeach; ?>
        </ul>
        <?php endif; ?>
<?php endif; ?>