<?php
/**
 * Created by PhpStorm.
 * User: aliyatulyakova
 * Date: 09/11/2017
 * Time: 11:56
 */

class Stores_RetailDirectory_Model_Resource_Retailstore_Collection extends Mage_Core_Model_Resource_Db_Collection_Abstract {
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub

        /**
         * Tell Magento the model and resource model to use for
         * this collection. Because both aliases are the same,
         * we can omit the second paramater if we wish.
         */
        $this->_init(
            'stores_retaildirectory/retailstore',
            'stores_retaildirectory/retailstore'
        );
    }
}